[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']

auto_detect_solc = false
solc = '0.8.21'
optimizer = true
optimizer_runs = 10_000

gas_reports = ['*']
verbosity = 2

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config